---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar-clone
  template:
    metadata:
      labels:
        app: hotstar-clone
    spec:
      containers:
      - name: hotstar-clone
        image: your/hotstar-clone-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017/hotstar"
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-clone
spec:
  selector:
    app: hotstar-clone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
